package com.ai.Resume.analyser.model;

import java.util.List;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/*
 * DTO for Resume ↔ Job Description Match Analysis
 *
 * This model stores:
 * - ATS compatibility
 * - resume-job alignment
 * - matched skills
 * - missing keywords
 * - AI recommendations
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
public class jdMatchDto {

    /*
     * Overall Resume ↔ JD Match Percentage
     * Example: 78
     */
    private int matchScore;

    /*
     * ATS Optimization Score
     * Example: 85
     */
    private int atsScore;

    /*
     * Skills found in both:
     * Resume + Job Description
     */
    private List<String> matchedSkills;

    /*
     * Important skills missing from resume
     */
    private List<String> missingSkills;

    /*
     * Strong areas detected in resume
     */
    private List<String> strengths;

    /*
     * Weak areas or missing improvements
     */
    private List<String> improvements;

    /*
     * AI-generated actionable recommendations
     */
    private List<String> recommendations;

    /*
     * Optional future extensions
     */

    // Resume summary generated by AI
    private String aiSummary;

    // Suggested job roles
    private List<String> recommendedRoles;

    // Resume quality level
    // Example: Beginner / Intermediate / Advanced
    private String resumeLevel;

    // AI confidence score
    private int confidenceScore;

    // Keyword optimization percentage
    private int keywordCoverage;

    // Technical skill score
    private int technicalSkillScore;

    // Communication/soft skills score
    private int softSkillScore;

    // Formatting and structure score
    private int formattingScore;

    // Recruiter readiness score
    private int recruiterReadiness;

    // Missing ATS keywords
    private List<String> missingKeywords;

    // Suggested certifications
    private List<String> suggestedCertifications;

    // Suggested projects
    private List<String> suggestedProjects;

    // Suggested technologies to learn
    private List<String> suggestedTechnologies;

    // Career growth recommendations
    private List<String> careerRecommendations;
}
